



var initializingHTML = "<div id='initializingProgress' > PageDown is initializing...</div>";

var followHTML = "<div id='removeFollowButton' > PageDown's finished initializing. Hotkeys are enabled. <br>Press '\\' to toggle them on/off. <br>Press 'i' to PageDown all columns. <br>Press 'u' to PageUp all columns. <br>Press 'o' to return all columns to top.  </span> &nbsp; <br> <div style='padding-top:5px;'><a href='https://journa.host/spencerdailey' class='twitter-follow-button' data-show-count='false' data-dnt='true'>By @spencerdailey</a></div></div>";

string_hotkeyToggleHTML = "<div id='wb__hotkeyReminder' >Reminder: <br>Press '\\' to enable HOTKEYS </div>";
      
      var string_hotkeyEnabled = "<div id='wb__hotkeyToggleOn' >Hotkeys enabled. <br>Press '\\' to toggle </div>";
      
      var string_hotkeyDisabled = "<div id='wb__hotkeyToggleOff' style=''>Hotkeys disabled. <br>Press '\\' to toggle </div>";
      
      theKid = document.createElement("span");
      theKid.innerHTML = initializingHTML + followHTML + string_hotkeyEnabled + string_hotkeyDisabled + string_hotkeyToggleHTML;

      // append theKid to the end of theParent
      document.body.appendChild(theKid);
      
      
      var PUI = document.getElementById("initializingProgress");
      
      PUI.style.position = "absolute";
      PUI.style.bottom = "50px";
      PUI.style.right = "150px";
      PUI.style.padding = "5px";
      PUI.style.opacity = "1";
      PUI.style.zIndex = "1000000";
      PUI.style.borderColor = "darkgreen";
      PUI.style.borderStyle = "solid";
      PUI.style.borderWidth = "1px";
      PUI.style.backgroundColor = "white";
      PUI.style.textAlign = "center";
      
      PUI.style.display = "none";
      
      var RFB = document.getElementById("removeFollowButton");
      
      RFB.style.position = "absolute";
      RFB.style.bottom = "50px";
      RFB.style.right = "150px";
      RFB.style.padding = "5px";
      RFB.style.opacity = "1";
      RFB.style.zIndex = "1000000";
      RFB.style.borderColor = "darkgreen";
      RFB.style.borderStyle = "solid";
      RFB.style.borderWidth = "1px";
      RFB.style.backgroundColor = "white";
      RFB.style.textAlign = "center";
      
      RFB.style.display = "none";
      
      var HKR = document.getElementById("wb__hotkeyReminder");
      
      HKR.style.position = "absolute";
      HKR.style.bottom = "50px";
      HKR.style.right = "150px";
      HKR.style.padding = "5px";
      HKR.style.opacity = "1";
      HKR.style.zIndex = "1000000";
      HKR.style.borderColor = "darkgreen";
      HKR.style.borderStyle = "solid";
      HKR.style.borderWidth = "1px";
      HKR.style.backgroundColor = "white";
      HKR.style.textAlign = "center";
      
      HKR.style.display = "none";
      
      var HTON = document.getElementById("wb__hotkeyToggleOn");
      
      HTON.style.position = "absolute";
      HTON.style.bottom = "50px";
      HTON.style.right = "150px";
      HTON.style.padding = "5px";
      HTON.style.opacity = "1";
      HTON.style.zIndex = "1000000";
      HTON.style.borderColor = "darkgreen";
      HTON.style.borderStyle = "solid";
      HTON.style.borderWidth = "1px";
      HTON.style.backgroundColor = "white";
      HTON.style.textAlign = "center";
      
      HTON.style.display = "none";
      
      var HTO = document.getElementById("wb__hotkeyToggleOff");
      
      HTO.style.position = "absolute";
      HTO.style.bottom = "50px";
      HTO.style.right = "150px";
      HTO.style.padding = "5px";
      HTO.style.opacity = "1";
      HTO.style.zIndex = "1000000";
      HTO.style.borderColor = "darkgreen";
      HTO.style.borderStyle = "solid";
      HTO.style.borderWidth = "1px";
      HTO.style.backgroundColor = "white";
      HTO.style.textAlign = "center";
      
      HTO.style.display = "none";

// Generated by CoffeeScript 1.9.0
(function() {
  
    var allColumnElements, checkIfColumnsLoaded, countOfDomChecks, dontForgetToCollapseSidebarHTML, followedBool, hideSideBar, function_hotkeyToggleHtml, initialize, listenToAlphaKeys, numberOfColumnsToTrack, numberOfUses, numberWrappedAndPushed, oldVersionBool, percentScroll, previousScrollPosition, timeHTMLpersists;
    
    
    percentScroll = 1;
    numberOfColumnsToTrack = 5;
    allColumnElements = [];
    numberWrappedAndPushed = 0;
    previousScrollPosition = 0;
    
    followedBool = false;
    
    numberOfUses = 0;
    
    hideSideBar = false;
    
    listenToAlphaKeys = true;
    
    countOfDomChecks = 0;
    
    checkIfColumnsLoaded = function() {
      allColumnElements = document.querySelectorAll(".column[aria-label] .scrollable");
      
      // allColumnElements = $(".column[aria-label] .scrollable"); // .slice(0, numberOfColumnsToTrack);
      if (countOfDomChecks > 3 && allColumnElements.length > 0) {
        return initialize();
      } else if (allColumnElements.length > numberOfColumnsToTrack) {
        return initialize();
      } else {
        countOfDomChecks++;
        return setTimeout(function() {
          return checkIfColumnsLoaded();
        }, 2500);
      }
    };
    
    
    
    function_hotkeyToggleHtml = function() {
      var string_hotkeyToggleHTML, idTag;
      
      if (listenToAlphaKeys) {
        
        HTO.style.display = "none";
        
        HTON.style.display = "block";
        
        
      } else {
        
        HTO.style.display = "block";
        
        HTON.style.display = "none";
        
      }
      
      // $(document.body).prepend(string_hotkeyToggleHTML);
      return setTimeout(function() {
        HTO.style.display = "none";
        HTON.style.display = "none";
      },3000);
    };
    
    dontForgetToEnableHotkeysHTML = function() {
      var string_hotkeyToggleHTML, idTag;
      
      
      HKR.style.display = "block";
      
      return setTimeout(function() {
        HKR.style.display = "none";
      },4000);
    };
    initialize = function() {
      
      var currentScrollPositionFromTop, followHTML, iCounter, tweetButtonHTML, verticalHeight, verticalHeightFull;
      
      var IP = document.getElementById("initializingProgress");
      
      IP.style.display = "none";
      
      var RFB = document.getElementById("removeFollowButton");
      RFB.style.display = "block";
      
      // wb__hotkeyToggleOn
      // wb__hotkeyToggleOff
      
      
      verticalHeightFull = window.innerHeight;
      
      verticalHeight = parseInt(verticalHeightFull * .87);
      
      iCounter = 0;
      currentScrollPositionFromTop = 0;
      
      
      document.onkeydown = function(event) {
          event = event || window.event;
          
      
      
      
        var columnEl, _i, _j, _k, _l, _len, _len1, _len2, _len3, _results, _results1, _results2, _results3;
        
        // console.log("Handler for .keydown() called.");
        // console.debug(event);
        
        if (event.key === 'i' && listenToAlphaKeys === false) {
          iCounter++;
          if (iCounter > 4) {
            dontForgetToEnableHotkeysHTML();
          }
        } else {
          iCounter = 0;
        }
        
        // console.log(iCounter);
        
        if (event.key === '\\') {
          
          if (listenToAlphaKeys == false){
          
            // $("#mastodon > div > div > div.columns-area > div.drawer").css('left', '0');
            // hideSideBar = true;
            listenToAlphaKeys = true;
            return function_hotkeyToggleHtml();
          } else {
            // $("#mastodon > div > div > div.columns-area > div.drawer").css('left', '');
            listenToAlphaKeys = false;
            // hideSideBar = false;
            return function_hotkeyToggleHtml();
          }
        } else if (listenToAlphaKeys === true) {
          if (event.key === 'y') {
            currentScrollPositionFromTop = previousScrollPosition;
            previousScrollPosition = 0;
            // _results = [];
            for (_i = 0, _len = allColumnElements.length; _i < _len; _i++) {
              columnEl = allColumnElements[_i];
              columnEl.scrollTop = currentScrollPositionFromTop;
            }
            // return _results;
          } else if (event.key === 'u') {
            previousScrollPosition = currentScrollPositionFromTop;
            currentScrollPositionFromTop -= verticalHeight;
            
            for (_j = 0, _len1 = allColumnElements.length; _j < _len1; _j++) {
              columnEl = allColumnElements[_j];
              columnEl.scrollTop = currentScrollPositionFromTop;
            }
            
          } else if (event.key === 'i') {
            
            // console.log("} else if (event.charCode ===");
            // console.log(listenToAlphaKeys);
            
            previousScrollPosition = currentScrollPositionFromTop;
            
            // console.log(currentScrollPositionFromTop);
            // console.log(verticalHeight);
            
            currentScrollPositionFromTop += verticalHeight;
            if (verticalHeight > currentScrollPositionFromTop) {
              currentScrollPositionFromTop = 0;
            }
            
            // console.log(currentScrollPositionFromTop);
            
            // console.log("allColumnElements.length");
            // console.log(allColumnElements.length);
            // console.log(allColumnElements);
            
            // allColumnElements[1].scrollTop = 40;
            
            for (_k = 0, _len2 = allColumnElements.length; _k < _len2; _k++) {
              columnEl = allColumnElements[_k];
              columnEl.scrollTop = currentScrollPositionFromTop;
            }
            
          } else if (event.key === 'o') {
            currentScrollPositionFromTop = 0;
            
            for (_l = 0, _len3 = allColumnElements.length; _l < _len3; _l++) {
              columnEl = allColumnElements[_l];
              columnEl.scrollTop = currentScrollPositionFromTop;
            }
            
          }
        }
      };
      
      setTimeout(function() {
            // var CLOSEBOX = document.getElementById("closeFollowBox");
            // CLOSEBOX.setAttribute('onclick','var RFB = document.getElementById("removeFollowButton");RFB.style.display = "none";');
            //  &nbsp; <span id='closeFollowBox' style='padding-left:4px; padding-right:4px; border-color:grey; border-style: solid; border-width:1px; color: grey;' >&#10006;</span>
            
                  var RFB = document.getElementById("removeFollowButton");
                  RFB.style.display = "none";
            
      },6100);
    };
    
    // this extension is only for the multicolumn interface
    if(window.location.href.indexOf("/deck/") != -1){
      setTimeout(function() {
        // Hotkeys enabled.
        
        PUI.style.display = "block";
        checkIfColumnsLoaded();
        
      },200);
    }
    
    
  

}).call(this);